### ISSUE TITLE
Contact page: 

### ISSUE THREAD

**Issue by spritle** [spritlesoftware/our-website#10]
Icon : Want to visit us? Here are the Google maps directions

-  Ohio, USA: https://goo.gl/maps/Q6pvbhR3KcYsKobu9
-  Singapore: https://goo.gl/maps/E5jypQYo5qzqC6ow8
-  Chennai, India:  https://g.page/spritlesoftware?share

**Comment by Prabhu-BA** [comment]
Google maps directions for all three locations are added so closing this task as completed
